version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
  angular: # name of the first service
    build: client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./client:/app # this will enable changes made to the angular app reflect in the container

  express: #name of the second service
    build: server # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forewarding
    links:
      - database